# Generated by Django 4.2.1 on 2023-09-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0014_auto_20200609_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='donacion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='donacion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
