# Generated by Django 4.2.1 on 2023-09-16 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_cliente_donacion_proveedor_donacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cantidad',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator(code='invalid_campo', message='Este campo solo puede contener letras, números y espacios.', regex='^[a-zA-Z0-9\\s]*$')]),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cantidad',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator(code='invalid_campo', message='Este campo solo puede contener letras, números y espacios.', regex='^[a-zA-Z0-9\\s]*$')]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('1', 'Donaciones en Efectivo'), ('2', 'Transferencias Bancarias'), ('3', 'Vales de Comida'), ('4', 'Otros')], max_length=20),
        ),
    ]
