# Generated by Django 4.2.1 on 2023-09-16 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_cliente_cantidad_proveedor_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='productos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='productos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.producto'),
        ),
    ]
