# Generated by Django 4.2.1 on 2023-09-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_cliente_productos_proveedor_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
